# Generated by Django 4.0.4 on 2022-06-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_myportfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolio',
            name='purchased_price',
            field=models.IntegerField(null=True),
        ),
    ]
