# Generated by Django 4.0.4 on 2022-06-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_myportfolio_purchased_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myportfolio',
            name='purchased_price',
            field=models.FloatField(null=True),
        ),
    ]
