# Generated by Django 4.0.4 on 2022-07-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_myportfolio_purchased_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_upload', models.FileField(upload_to='excel_upload/')),
            ],
        ),
    ]
