# Generated by Django 4.0.4 on 2022-07-03 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0005_excel_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel_upload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excel_upload',
            name='excel_upload',
            field=models.FileField(upload_to=''),
        ),
    ]
