# Generated by Django 4.0.4 on 2022-07-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_excel_upload_user_alter_excel_upload_excel_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_upload',
            name='excel_upload',
            field=models.FileField(upload_to='media/'),
        ),
    ]
